apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adguard
  namespace: flux-system
spec:
  interval: 30m
  path: ./apps/infrastructure/adguard
  prune: true # remove any elements later removed from the above path
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
