apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config-volume
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
